version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 32032:27017
  mongo-client:
    image: mongoclient/mongoclient:latest
    container_name: mongo-client
    hostname: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3333:3000