version: '3'

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - 32032:27017
    volumes:
      - ../_data/mongo-db:/data
  redis-scraping-session:
    image: redis:3.0
    container_name: redis-scraping-session
    restart: unless-stopped
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - 32033:6379
    volumes:
      - ../_data/scraping-session:/data
  mongo-client:
    image: mongoclient/mongoclient:latest
    container_name: mongo-client
    hostname: mongoclient
    depends_on:
      - mongo-db
    ports:
      - 3333:3000
volumes:
  mongodb-data:
  scraping-session-data:
