version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 32032:27017
  mongo-client:
    image: mongoclient/mongoclient:latest
    container_name: mongo-client
    hostname: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3333:3000
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "4545:4400"
    depends_on:
      - mongodb
    environment:
      PORT: 4400
      MONGODB_URL: mongodb://localhost:32032/
